originLat: 38.765824
originLon: -9.092815
vehicle:
  control:
    SURGE_TO_RPM: 101
  safety_features:
    max_depth: 5.0 # [m]
    min_altitude: 1.0 # [m]
    min_altitude_ref: 1.5 # [m]
    wifi_timeout: 10.0 # [s]
    acoustic_timeout: 15.0 # [s]

    