auv_sim:

  # General simulation environment constants
  fluid_density: 1.025 # (kg/l)

  # Vehicle dynamic parameters
  vehicle:
    mass: 30 # (kg)
    zg: 0.0 # center of gravity in body axis (m)
    vehicle_density: 1.0 # TO DEFINE LATER
    inertia_tensor: [1000.0, 1000.0, 4.14]  # diagonal (3x3) moment of inertia matrix (kg/m2)
    linear_damping_tensor: [0.0, -55.1, -4.1879, -3000.0, -3000.0, -4.14] # diagonal (6x6) matrix with linear damping
    quadratic_damping_tensor: [-27.5, -101.0, -40.9649,  -3000.0, -3000.0, -6.23] # diagonal (6x6) matrix with quadratic damping
    added_mass_tensor: [20.0, 30.0, 80.088, 0.0, 0.0, 0.5] # diagonal (6x6) matrix with added mass terms

    actuators:
      # For each thruster [Fx, Fy, Fz, lx, ly, lz] where F = forces and l = moments arms
      # and each line of the matrix represents a thruster
      allocation_matrix: [1.0, 0.0, 0.0, -0.25, -0.15, 0.0,
                          1.0, 0.0, 0.0, -0.25,  0.15, 0.0]

      # Thrusters parameter
      lump_param_positive: [0.00000177778, 0.0, 0.0]  # (a*|x|^{2} + b*|x| + c)
      lump_param_negative: [-0.00000177778, 0.0, 0.0] # (a*|x|^{2} + b*|x| + c)

      max_input: 100 # Maximum normalized input value
      min_input: 8.6 # Minimum normalized input value (for values < |min_input|) the motors "won't" spin <-> dead-zone

      # A gain used to scale the applied normalized input thrust (in this case used to convert from % to RPM)
      # This gain is mainly used to convert between scales
      gain: 45

      # Model of each thruster is the same as for a regular DC motor (pole+delay)
      pole: 7.2115
      delay: 0.345 # s

  # Oceans currents as a gaussian process
  current:
    mean: [0.0, 0.0, 0.0]
    sigma: [0.0, 0.0, 0.0]
    minimum: [0.0, 0.0, 0.0]
    maximum: [0.0, 0.0, 0.0]

world_frame: "mblack_world"
base_link: "mblack_base_link"

sensors:
    water_column: 100
    sensors:
        - type     : "GNSS"
          frame_id : "mblack_gnss"
          frequency: 10.0
          count    : 0        # After n measumerements sensor is discarded
          noise    : 0.00
          variance : 0.03
          debug    : true     # Full gps even when diving
        - type     : "DVL_BT"
          frame_id : "mblack_dvl_bt"
          frequency: 5.0
          noise    : 0.10
          variance : 0.05
          altitude : 30.0
          debug    : true     # works regardless of depth
          count    : 0
        - type     : "DVL_WT"
          frame_id : "mblack_dvl_wt"
          frequency: 5.0
          noise    : 0.01
          variance : 0.0
          altitude : 110.0
          count    : 0        # After n measumerements sensor is discarded
        - type     : "AHRS"
          frame_id : "mblack_ahrs"
          frequency: 5.0
          noise    : [0.051, 0.017]
          variance : 0.001
        - type     : "DEPTH"
          frame_id : "mblack_depth"
          frequency: 5.0
          noise    : 0.01
          variance : 0.005
          count    : 0        # After n measumerements sensor is discarded
        - type     : "ALTIMETER"
          frame_id : "mblack_altimeter"
          frequency: 5.0
          noise    : 0.1
          variance : 0.01
          count    : 0
        - type     : "MODEL"
          frequency: 10.0
